// <auto-generated/>
using EcoMeal.Site.Models;
using EcoMeal.Site.Services;
using Microsoft.AspNetCore.Components;

namespace EcoMeal.Site.Components.Pages
{
    public partial class AddPackage
    {
        [Parameter]
        public int BusinessId { get; set; }
        [Inject]
        public PackageService PackageService { get; set; }
        [Inject]
        public PackageTypeService PackageTypeService { get; set; }
        [Inject]
        public NavigationManager NavigationManager { get; set; }
        private List<PackageTypesModel> PackageTypes;
        public PackageAddModel PackageAddModel { get; set; } = new PackageAddModel()
        {
            Name = string.Empty,
            Description = string.Empty,
            Price = 0,
            StartPickup = DateTime.Now,
            EndPickup = DateTime.Now.AddHours(2)
        };
        protected override async Task OnInitializedAsync ()
        {
            PackageTypes = await PackageTypeService.GetAll();
            PackageTypes = PackageTypes ?? new List<PackageTypesModel> ();
        }
        public async Task AddPackageInService ()
        {
            await PackageService.AddToBusiness(BusinessId, PackageAddModel);
            NavigationManager.NavigateTo(uri: $"business/{BusinessId}");
        }
    }
}