// <auto-generated/>
using EcoMeal.Site.Models;
using EcoMeal.Site.Services;
using Microsoft.AspNetCore.Components;

namespace EcoMeal.Site.Components.Pages
{
    public partial class UpdatePackage
    {
        [Parameter]
        public int BusinessId { get; set; }
        [Inject]
        public BusinessService BusinessService { get; set; }
        [Inject]
        public NavigationManager NavigationManager { get; set; }
        private List<PackageTypesModel> PackageTypes;
        public PackageAddModel PackageAddModel { get; set; }
        protected override async Task OnInitializedAsync ()
        {
            PackageTypes = await BusinessService.GetPackageTypes();
            PackageTypes = PackageTypes ?? new List<PackageTypesModel> ();
            package = BusinessService.GetPackageById(Id);
            PackageAddModel =  = new PackageAddModel()
            {
                Name = package.Name,
                Description = package.Description,
                Price = package.Price,
                StartPickup = package.StartPickup,
                EndPickup = package.EndPickup
            };
        }
        public async Task UpdatePackageInService ()
        {
            await BusinessService.AddPackageToBusiness(BusinessId, PackageAddModel);
            NavigationManager.NavigateTo(uri: $"business/{BusinessId}");
        }
    }
}