// <auto-generated/>
using EcoMeal.Site.Models;
using EcoMeal.Site.Services;
using Microsoft.AspNetCore.Components;
using System.ComponentModel.DataAnnotations;

namespace EcoMeal.Site.Components.Pages
{
    public partial class UpdatePackage
    {
        [Parameter]
        public int PackageId { get; set; }
        [Parameter]
        public int BusinessId { get; set; }
        [Inject]
        public required AppService AppService { get; set; }
        [Inject]
        public PackageService PackageService { get; set; }
        [Inject]
        public PackageTypeService PackageTypeService { get; set; }
        [Inject]
        public NavigationManager NavigationManager { get; set; }
        private List<PackageTypesModel> PackageTypes;
        public PackageAddModel PackageAddModel { get; set; } = new PackageAddModel()
        {
            Name = String.Empty,
            Description = String.Empty
        };
        protected override async Task OnInitializedAsync ()
        {
            Console.WriteLine(BusinessId);
            PackageTypes = await PackageTypeService.GetAll();
            PackageTypes = PackageTypes ?? new List<PackageTypesModel> ();
            var package = await PackageService.GetOneById(PackageId);
            PackageAddModel = new PackageAddModel()
            {
                Name = package.Name,
                Description = package.Description,
                Price = package.Price,
                StartPickup = package.StartPickup,
                EndPickup = package.EndPickup,
                PackageTypeId = package.PackageTypeId
            };
        }
        public async Task UpdatePackageInService ()
        {
            //Console.WriteLine(BusinessId);
            await PackageService.Update(PackageId, PackageAddModel);
            AppService.Message = "Ai editat cu succes pachetul!";
            NavigationManager.NavigateTo(uri: $"business/{BusinessId}");
        }
    }
}